version: '3'
services:
  web:
    container_name: rails
    build: .
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
    command: /bin/sh -c "bundle install; rm /usr/src/app/tmp/pids/server.pid; rails s -b 0.0.0.0 -p 3000"
    environment:
    - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
    depends_on:
      - selenium_chrome
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
  smtp:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

